version: '3'
services:
  postgres_db:
      container_name: postgres
      image: postgres:latest
      restart: always
      ports:
          - 5432:5432
      environment:
        - DATABASE_HOST=localhost
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - ./postgres:/var/lib/postgresql/data